- release-notes.md
Ready to release RocketMQ Go Client 2.0.0-alpha2
Add release note for 2.0.0-alpha2
> [ISSUE #75] Add release note for 2.0.0-alpha2

- internal/utils/files.go
```go
func MakeFileIfNotExist(path string) error {
//when path is not exist,  info: nil   err:  error | *os.PathError
info, err := os.Stat(path) 
if err != nil {
if os.IsNotExist(err) {
if err = os.MkdirAll(path, 0755); err != nil {
return err
}
}
}
// info still nil after mkdir
if !info.IsDir() {
return errors.New(path + " is a file")
}
return nil
}
```
> [ISSUE #144] Fix nil pointer when file not exist

- consumer/consumer.go
- consumer/offset_store.go
- consumer/offset_store_test.go
- consumer/push_consumer.go
- internal/client.go
- internal/mock_client.go
- internal/remote/future.go
- internal/remote/mock_remote_client.go
- internal/remote/remote_client.go
- internal/remote/remote_client_test.go
- internal/route.go
- internal/route_test.go
- internal/trace.go
- producer/producer.go
- producer/producer_test.go
Support ctx of rmqClient and remoteClient
> [ISSUE  #176]add ctx to rmqClient & remoteClient

- go.sum
- primitive/message.go
- primitive/message_test.go
[ISSUE #211] Fix UnmarshalMessageID function. 
Implment GetAddressByBytes function.
Convert MessageID to IP:port and offset. The implementation refers to JAVA code.
The IP address which stores in 4byte array, not 8 bytes.
The unit-test case from my company online data.
> [ISSUE #211]fix unmarhsal messageID bug

- consumer/push_consumer.go
In consumer/push_consumer.go, somewhere output ("xxxxxxx %v,%v", p1, p2),  use rlog.Info/rlog.Warn other than rlog.Infof/rlog.Warnf, fixed it.
- [√] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [√] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not …
> fixed log function

- consumer/push_consumer.go
- register consumer before defaultConsumer start]
Closes #194
> [ISSUE #194]fix: avoid extra err info on pushConsumer startup

- consumer/strategy.go
- go.mod
- go.sum
- replace stathat.com/c/consistent for github.com/stathat/consistent,
which is free to download
Closes #243
> [ISSUE #243]fix: replace consistent package

- .travis.yml
- core/api_test.go
- core/version.go
- core/version_test.go
- demos/main.go
- demos/orderly_push_consumer.go
- demos/producer.go
- demos/producer_orderly.go
- demos/push_consumer.go
ISSUE #223 
fix(travis):remove unnessary script in travis.yml
> fix(travis):remove unnessary script in travis.yml

- core/api.go
- core/api_test.go
- core/push_consumer.go
…n and remove useless client config GroupName
fix #250 
- GroupName in clientConfig  is useless
- Subscribe method is not based on the last subscription
- Subscribe method can pass in nil consumeFunc parameter
- Delete GroupName
- User can subscribe to the same topic multiple times, and the last subscription shall prevail.
- User can not subscribe with nil consumeFunc parameter
> [ISSUE 250] Delete uesless GroupName and make subscribe method correct

- internal/client.go
- internal/utils/string.go
if consumer subscribe with tag may cause hashcode int overflow
> fix(PushConsumer):fix the consumer subscripe with tag

- internal/route.go
Resolve unable to get broker addr when a new topic
support broker addr search by default topic
yes
> support broker addr search by default topic

- consumer/consumer.go
- consumer/process_queue.go
- consumer/push_consumer.go
- internal/client.go
- internal/mock_namesrv.go
- internal/model.go
- internal/model_test.go
- internal/namesrv.go
- internal/request.go
see detail: https://github.com/apache/rocketmq-client-go/issues/301
> [ISSUE #301] Adding GET_CONSUMER_RUNNING_INFO

- consumer/push_consumer.go
Fixed multi-client Rebalance blocking problem
> Prevent pc.prch blocking

- internal/client.go
- internal/mock_client.go
- internal/mock_namesrv.go
- internal/namesrv.go
- internal/route.go
- producer/producer.go
- fix producer publish update logic
- fix consumer subcription update logic
Closes #338
> [ISSUE #338] fix(route): update route

- examples/producer/transaction/main.go
- internal/callback.go
- internal/client.go
- primitive/message.go
- producer/producer.go
1. change TransactionListener  param from struct to struct pointer
2. change CheckLocalTransaction msg member from strucut to pointer, and pass it's pointer to channel order than value
3. add judge before log error in checkTransactionState()
I just use examples/producer/transaction/main.go to test it, and I think should not  hidden bugs after I test and read context code.
#340
> [ISSUE #340] change transaction producer interface signature

- consumer/consumer.go
- consistent with java
Closes #389
> [ISSUE #389] feat(consumer): move updatePullFromWhichNode ahead of result check

- consumer/consumer.go
通过 `mqadmin consumerStatus` 查看消费者状态时，命令执行失败。
```
$ NAMESRV_ADDR=localhost:9876 sh bin/mqadmin consumerStatus -g testGroup                                                                                                                                   (rocketmq-all-4.5.2*) 13:37:07
RocketMQLog:WARN No appenders could be found for logger (io.netty.util.internal.PlatformDependent0).
RocketMQLog:WARN Please initialize the logger system properly.
001  172.17.200.98@DEFAULT                    V4_5_2               1578980233054/172.17.200.98@DEFAULT
org.apache.rocketmq.tools.command.SubCommandException: ConsumerStatusSubCommand command failed
at org.apache.rocketmq.tools.command.consumer.ConsumerStatusSubCommand.execute(ConsumerStatusSubCommand.java:134)
at …
```
> fix: consume type compatible with protocol

- consumer/process_queue.go
- move int64 to struct top
Closes #396
> [ISSUE #396] fix(core): unalign field panic when atomic operation

- internal/route.go
default Topic is extra for UpdateTopicRouteInfo, and will cause incorrect config to retry topic.
Closes #404
> [ISSUE #404] feat(nameserver): correct impl of UpdateTopicRouteInfo

- consumer/consumer.go
close #419 
the message queue list got from the broker should be sort by ASC before do rebalance.
> fix(strategy): change the deafult mq sort to ASC when do rebalance.

- .travis.yml
fix(travisci): use archive server to avoid download rocketmq package failed
> fix(travisci): use archive server to avoid download rocketmq package failed

- primitive/message.go
- primitive/pool.go
- primitive/result_test.go
- use sync.pool of bytes.Buffer instead of new
Closes #407
> [ISSUE #407] feat: reuse bytes.Buffer

- examples/producer/simple/main.go
- internal/client.go
- internal/mock_namesrv.go
- internal/namesrv.go
- internal/route.go
- primitive/errors.go
- producer/option.go
- producer/producer.go
> [ISSUE #415] feat(producer): auto create topic for producer

- internal/client.go
- internal/route.go
- producer/producer.go
UpdateNameServerAddress shoule be called before producer start, or namesrvs list will be empty, lead to a panic。
Case: in private enviroment, start a consumer first, then start a producer, call publish. There whould be a panic.
> fix(producer): UpdateNameServerAddress shoule be called before producer start, or namesrvs list will be empty, lead to a panic

- core/error.go
- core/producer.go
- core/transaction_producer.go
Closes #460 
1. Fix typo error : cproduer -> cproducer.
2. Expose error message API for debugging [:( When $HOME is not set, the producer could not start. This cost me a lot time to find WHY]. Such AS: [boost::filesystem::create_directories: Permission denied: "//logs/rocketmq-cpp]
> [ISSUE #460] Add GetLatestErrorMessage for debugging and fix typo in producer.

- examples/consumer/trace/main.go
- examples/producer/trace/main.go
- internal/trace.go
- primitive/trace.go
support ns-resolver config in TraceConfig
close https://github.com/apache/rocketmq-client-go/issues/473
> [ISSUE #473] support nsresolver in TraceConfig

- internal/trace.go
- primitive/result.go
- producer/producer.go
1. set the default value of SendResult.Status to SendUnknownError
2. fix panic: select queue with nil
> set default of SendResult.Status and fix panic

- consumer/consumer.go
ensure consume correctly from retry topic
- initialize offset 0 when start up
> [ISSUE #530] fix: initialize 0 for retry topic when ConsumeFromLastOffst

- consumer/consumer.go
Fix [Issue #553](https://github.com/apache/rocketmq-client-go/issues/533)
Two places call FindBrokerAddrByName function to pass parameters typo error
Check the input parameter is modified to "mq.BrokerName".
> Fix: FindBrokerAddrByName input parameter problem

- rlog/log.go
user can customize mq client log output path.
> support set log output path

- internal/namesrv.go
in same cases, such as addr="http://tim.test.com:9876", then
strings.TrimLeft(addr, "http(s)://") will get "im.test.com:9876" instead
of "tim.test.com:9876"
Signed-off-by: pengfei <julien.zpf@alibaba-inc.com>
bugfix
XX
XXXX
> [#540] Fix parse address error when address has prefix "t"

- internal/remote/remote_client.go
Change-Id: Ifa0555c45529f84720ef885e5f803f8633e65968
What is the purpose of the change
fix the goroutine leak for remotingClient.
In the case that ResponseFuture timed out, goroutine would be leak.
Brief changelog
if ResponseFuture times out，DONE channel should be closed。
> fix(remote_client):avoid goroutine leak

- core/message.go
[ISSUE #576] Fix get message property failed after it is set to go msg struct.
close #576 
Get from local msg first before getting from c struct.
> [ISSUE #576] Fix get message property failed after it is set to go msg struct.

- consumer/push_consumer.go
fix possible infinite loop after rebalance
it's very likely there will be cpu/memory drain caused by dead loop after a rebalance
this fix addressed the issue by check whether the process queue is already dropped before starting next consume
> fix possible infinite loop after rebalance

- internal/remote/codec.go
- internal/remote/remote_client.go
- internal/remote/tcp_conn.go
improve produce performance
reduce 1 memory copy on doRequest
XXXX
> feat(produce) : reduce memory copy for on-wire protocol

- consumer/process_queue.go
ref https://github.com/apache/rocketmq-client-go/issues/615
> [ISSUE #615]fix: putmessage should check msg in consumingMsgOrderlyTreeMap

- consumer/push_consumer.go
- internal/client.go
- internal/model.go
- internal/model_test.go
- internal/request.go
issue #621 
Add func ConsumeMessageDirectly
Add unit test
XXXX
> [ISSUE #621] Support consume message directly

- consumer/push_consumer.go
- consumer/push_consumer_test.go
issue #487 
Implement Unsubscribe method for push consumer
XXXX
> [ISSUE #487] Implement Unsubscribe method for push consumer

- benchmark/consumer.go
- benchmark/producer.go
issue #596 
1. Fix benchmark command register conflict
2. Add code for producer and consumer to truly send and consume
XXXX
> [ISSUE #596] Fix command register conflict, add consumer and producer logic code

- primitive/message.go
- producer/producer.go
close https://github.com/apache/rocketmq-client-go/issues/617
Signed-off-by: Tenhan Lee <tenhanlee@gmail.com>
Solved the memory leak problem with AliyunRocketMQ
1. checkTransactionState: retrieve transactionid from property first 
2. add message key: PropertyTransactionID = "__transactionId__" (which AlibabaRocketMQ uses)
This change is only for RocketMQ of Alibaba Cloud and will not break the original logic.
- [√] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). …
> [ISSUE #617] retrieve transactionid from property first

- producer/selector.go
fix crash on selecting queue.
https://github.com/golang/go/blob/a7e16abb22f1b249d2691b32a5d20206282898f2/src/math/rand/rand.go#L7-L20
The default Source is safe for concurrent use by multiple goroutines, but Sources created by NewSource are not.
如上所述，math/rand中通过NewSource创建的rand方法不是线程安全的。多协程发送消息时，不加锁的情况下同时select queue会因数组越界导致panic。
panic如下：
panic： runtime error: index out of range [-1]
> fix: fix crash on selecting queue.

- internal/remote/codec.go
see: https://github.com/apache/rocketmq-client-go/issues/635
Use `io.ReadFull()` to read bytes instead of `binary.Read()`.
> [ISSUE #635] Improving decoding performance for remoting commands

- producer/selector.go
see #651 
Aquire lock before accessing the `indexer`.
> [ISSUE #651] fix an issue where a map read operation was not protected by the lock

- internal/trace.go
- internal/trace_test.go
issue #585 
1. Add ClientHost field and GroupName field to traceBean
XXXX
> [ISSUE #585] Fix the wrong StoreHost and GroupName with consume trace message

- consumer/consumer.go
- consumer/process_queue.go
issue #614 
1 close msg channel when consumer closed with RWMutex
2 check if process queue is dropped before write to msg channel
XXXX
> [ISSUE #614] Fix go routine leaks when consumer close with msg channel blocked

- internal/request.go
#683 
- 将DefaultTopicQueueNums字段类型由string改为int
修复前：
修复后：无错误日志
> [ISSEU 683]request parameter type error fix

- consumer/pull_consumer.go
The `sync.Map` store the value 0, its type is `int`, but in that code before fixed, the value `Load` by `sync.Map` is asserted as `int64`, so cause the type assert panic.
> [ISSUE #688] fix: type assert panic

- internal/client.go
- internal/remote/remote_client_test.go
- internal/route.go
- internal/trace.go
- producer/producer.go
Although the the resources associatd with the context created by context.WithTimeout will be release after the timer elapsed, but call cancel() to release the resources as soon as possible can avoid context/memory leak.
> [ISSUE #698] fix: call cancel() as soon as possible to release the resources associatd with context

- internal/utils/net.go
Resolved #637.
By filtering the loopback type and the non-up state of the interface, we can get a correct and available client IP.
```bash
go test -v internal/utils/net.go internal/utils/net_test.go 
```
> [ISSUE #637] Fix filter lookback interface for utils.ClientIP

- consumer/push_consumer.go
issue #659 
make consumeMessageBatchMaxSize default value consistent with java client
XXXX
> [ISSUE #659] make consumeMessageBatchMaxSize default value consistent with java client

- producer/producer.go
> [ISSUE #701] Fix  timeout of SendAsync

- producer/interceptor.go
#710 in trace interceptor, if TraceTopicName equals current message topic then message will be send twice
XX
XXXX
> [ISSUE #710] Fix send duplicate message in trace interceptor

- consumer/push_consumer.go
Relates to PULL #619 
fixes #650 #618 
When `SuspendCurrentQueueAMoment` is returned for orderly consumption, `makeMessageToCosumeAgain` should be used instead of `putMessages`, just like the java counterpart.
None
> [ISSUE #650] fix: correctly mark messages to be reconsumed

- errors/errors.go
- producer/producer.go
- producer/producer_test.go
issue #744 
Because of the lack of pre-check, the message will be sent to the first topic when batch sending messages to multiple topics.
add check logic in func [ defaultProducer.checkMsg(msgs ...*primitive.Message) error ]
> [ISSUE #744] check multiple topics in one batch

- internal/remote/remote_client.go
- primitive/pool.go
https://github.com/apache/rocketmq-client-go/issues/757
XX
XXXX
> [ISSUE #757] Fix GetHeader type conflict

- consumer/manual_pull_consumer.go
- consumer/manual_pull_consumer_test.go
- examples/consumer/manual/main.go
- internal/request.go
- primitive/interceptor.go
#737
add ManualPullConsumer
> `internal.RMQClient` is still used, and you can see if it is refactored later in this part.
XXXX
> [ISSUE #737] Add ManualPullConsumer

- internal/model.go
- internal/model_test.go
See #759
1. change resetOffsetBody parse logic. support both gson and fastjson schema.
start push consumer and trigger reset offset by mqadmin tool
> [ISSUE #759] Change ResetOffsetBody response parse method to support fastjson schema

- admin/admin.go
- consumer/consumer.go
- consumer/consumer_test.go
- consumer/interceptor.go
- consumer/pull_consumer.go
- consumer/push_consumer.go
- internal/client.go
- internal/mock_client.go
- internal/mock_namesrv.go
- internal/namesrv.go
- internal/route.go
- internal/trace.go
- producer/interceptor.go
- producer/option.go
- producer/producer.go
- producer/producer_test.go
- rlog/log.go
> Refactor the client instance struct，converge the namesrv module

- admin/admin.go
- consumer/pull_consumer.go
- consumer/push_consumer.go
- internal/client.go
- internal/namesrv.go
- internal/namesrv_test.go
- internal/remote/remote_client.go
- internal/remote/remote_client_test.go
- internal/remote/tcp_conn.go
- internal/route_test.go
- internal/trace.go
- producer/producer.go
fix #817
1. add tcp conn write and read deadline to avoid long time block socket ops when remote endpoint crash.
2. enable tcp keep alive.
3. remove request from responseTable when InvokeAsync.
4. doRequest close socket connection with destory call.
> fix long time block when remote endpoint crash.

- go.mod
- go.sum
- rlog/log.go
fix #828 
support rlog rotate
see https://stackoverflow.com/a/67495666
rlog.Config can support max file size max retention time etc. just try.
> [ISSUE #828] Support rlog rotate

- consumer/push_consumer.go
- internal/client.go
- internal/model.go
- internal/request.go
fix #827 
Support get consumerRunningInfo return goroutine stack
support GetConsumerRunningInfo Rpc, add jstack parameter.
./mqadmin consumerStatus -g testGroup -n :9876 -s true -i 192.168.0.105@8851
show current program goroutine stack.
> [ISSUE #827] Support get consumerRunningInfo return goroutine stack

- consumer/option.go
Fix some params for consumer can not be changed
- ConsumeTimestamp: the default value should be 30 minutes before now.
- ConsumerPullTimeout 
- ConsumeConcurrentlyMaxSpan 
XX
> fix some params for consumer can not be changed

- consumer/consumer.go
- consumer/consumer_test.go
- consumer/mock_offset_store.go
- consumer/offset_store.go
- consumer/offset_store_test.go
- consumer/pull_consumer.go
- consumer/push_consumer.go
fix #832 
To expose the error thrown when client failed to get offset from broker
- add `readWithException` to `OffsetStore` and deprecate `read`
- add `computePullFromWhereWithException` to `defaultConsumer` and deprecate `computePullFromWhere`
- test files to use new methods
- add a 60s sleeping time to broker's `ConsumerOffsetManager.queryOffset` function, start this broker
- start consumer and check if the consumer's offset is set to minLogicOffset
> [ISSUE #832] Client may submit wrong offset when network instability

- producer/producer.go
[BUGFIX] selectMessageQueue nil *internal.TopicPublishInfo
just fix selectMessageQueue function  check nil *internal.TopicPublishInfo return nil
> fix: selectMessageQueue nil *internal.TopicPublishInfo

- consumer/push_consumer.go
- internal/trace.go
- producer/producer.go
fix #774
current trace data can't send success.
only cancel context when receive error or request finished.
with this patch trace data can send succes.
> [ISSUE #774] Avoid cancel context too early cause trace data fail.

- consumer/process_queue.go
fix https://github.com/apache/rocketmq-client-go/issues/628
make sure takeMessages can quit when pull request is droped or longtime no message
takeMessages sleep max 5s
start consumer and make sure no msg for consumer, consumer can quit takeMessage sleep
> [ISSUE #628]takeMessages sleep max 5s

- consumer/statistics.go
- consumer/statistics_test.go
Fix DATA RACE when running the executable file generated by `go build -race`
send csListLock *sync.Mutex to computeStatsData for lock csList
Run the following test with `go test -race` 
```
func TestNewStatsManager(t *testing.T) {
stats := NewStatsManager()
st := time.Now()
for  {
stats.increasePullTPS("rocketmq", "default", 1)
time.Sleep(500*time.Millisecond)
if time.Now().Sub(st) > 5*time.Minute {
break
}
}
stats.ShutDownStat()
}
```
The **DATA RACE** will print on terminal
```
WARNING: DATA RACE
Read at 0x00c000538028 by goroutine 230:
container/list.(*List).Len()
/usr/local/go1.17.3/src/container/list/list.go:66 +0xc7
github.com/apache/rocketmq-client-go/v2/consumer.computeStatsData()
/home/icey/lmm/v9-git/miot-services/lmm/rocketmq-client-go/consumer/statistics.go:143 +0xd5 …
```
> [ISSUE #819] Fix sis.samplingInSeconds and sis.printAtMinutes() running in different goroutines cause DATA RACE

- producer/producer.go
I streamlined the code of the encodeBatch() method and removed the else branch. The reasons are as follows:
The first line of encodeBatch() judges the case where len == 1. According to the judgment condition of if, else should take effect when len < 1 (ie len == 0). But the case of len == 0 is judged by checkMsg() before using the encodeBatch() method. Personally think that encodeBatch can be simplified.
Of course, the original author may need to keep the else branch from the perspective of code specifications or language features.
我精简了encodeBatch()方法的代码，删除了else分支。原因如下：
encodeBatch()第一行判断了 len == 1的情况。根据if的判断条件，else应该是len < 1时生效（即len == 0）。 但在使用encodeBatch()方法之前通过checkMsg()判断了len == 0的情况。 个人认为可以精简encodeBatch。
当然，原作者可能从代码规范或者语言特性方面考虑，需要保留else分支。
> Maybe can remove some useless code in encodeBatch()

- consumer/push_consumer.go
fix NOT_CONSUME_YET status message problem
when consumer include tag info, our's mq service have many NOT_CONSUME_YET status message
> [ISSUE #840]consumer consume include tag according to accumulation

- consumer/push_consumer.go
fix #813 
mqadmin consumerStatus command should get consumeRT related metrics. but current code return all 0.0
parameter pass to method wrong.
mqadmin consumerStatus  now show value not 0.0
> [ISSUE #813] Fix bug when get `mqadmin consumerStatus` can't get consume status.

- consumer/push_consumer.go
> [ISSUE #797] Fix msg lost if consumer crash when send msg back failed.

- consumer/process_queue.go
> [ISSUE #754] close msgCh when pq droped

- go.mod
- go.sum
close #864 
update rlog to 1.9.0 to fix CVE-2022-29526 in golang.org/x/sys
> [ISSUE #864] update rlog to 1.9.0 to fix CVE-2022-29526 in golang.org/x/sys

- consumer/process_queue.go
- consumer/push_consumer.go
fix #790
in golang direct read from atomic int64 will cause data race
see https://stackoverflow.com/questions/54090404/what-is-causing-this-data-race
> [ISSUE #790] use uber atomic lib to avoid atomic value data race.

- consumer/push_consumer.go
- consumer/push_consumer_test.go
[ISSUE #884]fix goroutine leak
[ISSUE #884]fix goroutine leak
[ISSUE #884]fix goroutine leak
>  [ISSUE #884]fix goroutine leak

- consumer/option.go
- consumer/push_consumer.go
- make some configs can be set
- add `ConsumeGoroutineNums` to control the number of goroutines that are consuming.
XX
XXXX
> Add param which like consumeThreadMin of java sdk to control consumption rate

- consumer/offset_store.go
- internal/response.go
when i start a new group to consume an old topic
i got some error logs
```
"[RocketMQ] msg: fetch offset of mq from broker error \n fields: map[MessageQueue:MessageQueue [topic=demo-topic, brokerName=broker-master, queueId=2] consumerGroup:rocketmq-EE10 underlayError:broker response code: 22, remarks: Not found, V3_0_6_SNAPSHOT maybe this group consumer boot first]"
"[RocketMQ] msg: do defaultConsumer, add a new mq failed \n fields: map[MessageQueue:MessageQueue [topic=demo-topic, brokerName=broker-master, queueId=2] consumerGroup:rocketmq-EE10]"}
```
then i find 
https://github.com/apache/rocketmq-client-go/blob/master/consumer/consumer.go:770
```
lastOffset, err := dc.storage.readWithException(mq, _ReadFromStore)
if err != nil {
// 这里 lastOffset = -1
return lastOffset, err
}
```
if the …
> [feat] fix query not found

- consumer/process_queue.go
fix consumer doesn't consume message because of blocked on Lock in so…
#897
> [ISSUE #897] fix consumer doesn't consume message because of blocked on Lock

- consumer/limiter.go
- consumer/option.go
- consumer/push_consumer.go
- internal/utils/namespace.go
Add user defined consume rate limiter which is topic dimension. The user could use self defined Limiter 'block' consume to controller topic consume rate based on  TPS / Concurrent / Load or any other condition.
- add consumer Limiter func definition.
- add Limiter to push_consumer#consumeMessageCurrently 
https://github.com/apache/rocketmq-client-go/issues/896
> (feat): add user defined topic dimension consumer limiter

- internal/route.go
#845
because  https://github.com/apache/rocketmq/pull/4432  change route info to standard json such as:
`{"brokerDatas":[{"brokerAddrs":{"0":"127.0.0.1:10911"}]}`
the old is:
`{"brokerDatas":[{"brokerAddrs":{0:"127.0.0.1:10911"}]}`
XX
XXXX
> [ISSUE #845] support standard json

- internal/trace.go
> [ISSUE #899]Fix the groupName takes the namespace prefix

- consumer/interceptor.go
- consumer/option.go
- consumer/push_consumer.go
- producer/interceptor.go
- producer/option.go
- producer/producer.go
> [ISSUE #901]Close the traceDispatcher when producer or consumer is shutdown

- consumer/push_consumer.go
add gotorutine restriction for limiter, avoid creating goroutine excessively.
push_consumer.go
XXXX
> [ISSUE #953] fix limiter with goroutine cover

- consumer/offset_store.go
> [ISSUE #986]Reduce the log level when fetch offset success and remove unnecessary mq

- internal/client.go
- producer/producer.go
fix https://github.com/apache/rocketmq-client-go/issues/996
add 2 operation when async process send resp error:
1. invoke user callback 
2. return error info to user
XXXX
> [ISSUE #996] invoke user callback and return error info when async process send resp error

- internal/client.go
The client version mismatch when using branch master<c8d06a66>
> fix: client version mismatch

- admin/admin.go
- admin/response.go
- examples/admin/group/main.go
- examples/admin/topic/main.go
- internal/client.go
- internal/mock_client.go
- internal/request.go
> [ISSUE #999]support admin topicList and groupList method

- primitive/message.go
- primitive/message_test.go
> [ISSUE #1030] Avoid to append unexpected separator to message key

- internal/client.go
caused by missing ref count
fix #1018 
revert #888 
XXXX
> [ISSUE #1018] Fix unintended shutdown of shared rmqClient

- consumer/mock_offset_store.go
- consumer/offset_store.go
- consumer/pull_consumer.go
- consumer/push_consumer.go
- internal/client.go
- internal/model.go
- internal/request.go
Support RequestCode `GET_CONSUMER_STATUS_FROM_CLIENT`
- Broker RequestCode `INVOKE_BROKER_TO_GET_CONSUMER_STATUS` will invoke each individual consumer to get
which message queues the consumer instance is processing
- Client is supposed to handle `GET_CONSUMER_STATUS_FROM_CLIENT` from Broker to return the Map of `<MessageQueue, MemoryOffset>` for the purpose of previous step
- `push_consumer` `pull_consumer` implements `getConsumerStatus(topic string, group string) *ConsumerStatus` 
- `offset_store` implements `getMQOffsetMap(topic string) map[primitive.MessageQueue]int64` for consumer to get the `MQOffsetMap`
XXXX
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not …
> support RequestCode GET_CONSUMER_STATUS_FROM_CLIENT

- consumer/push_consumer.go
The newly added parameter ConsumeGoroutineNums should allow to achieve the effect of not limiting the number of go routines as before.
The maximum number of 1000 is relatively small. If the performance of the machine is better, it may affect the maximum capacity of consumption.
[rocketmq-client-go/consumer/push_consumer.go](https://github.com/apache/rocketmq-client-go/blob/25003f6f083d3347a169ceb472295c272fbdf7a6/consumer/push_consumer.go#L606-L612)
ConsumeGoroutineNums should allow large values to be set, detail see 
https://github.com/apache/rocketmq-client-go/pull/883#issuecomment-1527143686
> change ConsumeGoroutineNums max value allowed

- consumer/option_test.go
- primitive/nsresolver.go
- producer/option_test.go
DomainWithUnit support existed query parameters
> DomainWithUnit support existed query parameters

- internal/response.go
- producer/producer.go
- producer/producer_test.go
- producer/selector.go
- producer/selector_test.go
> [ISSUE #1013] Fix: select one message queue of different broker when retry to send

- internal/client.go
fix the topic publishInfo and subscribeInfo not update bug
> fix: topic pubishInfo and subscribeInfo not update

- primitive/nsresolver.go
- primitive/nsresolver_test.go
fix https://github.com/apache/rocketmq-client-go/issues/1098
> [ISSUE #1098] HttpResolver snapshot file will be overwritten and mixed if multiple consumers or producers use different name server domains

- consumer/consumer.go
- consumer/option.go
- consumer/pull_consumer.go
- consumer/push_consumer.go
At present, there are two ways to control the rate of consumption, one is to limit consumer goroutine number (or the increased load on the machine slowed it down), and the other is to set `pullInterval` and `batchSize`.
Because the second way is easier to estimate the maximum consumption tps, we generally use the second one.
but the inconvenient thing is that when the backlog is relatively large, if we want to accelerate the consumption speed, we have to change the code and publish, the expansion of the machine can not solve the problem. 
The java version can dynamically set the pull interval, but the go version cannot be dynamically modified. For convenience, the maximum consumption tps setting of a single machine is supported.
```
Principle of flow control: 
pull TPS = …
```
> feat: support consumer consume tps option

- admin/admin.go
- consumer/option.go
- examples/consumer/tls/main.go
- examples/producer/tls/main.go
- internal/remote/remote_client.go
- internal/remote/tcp_conn.go
- producer/option.go
> [ISSUE #950] support tls connection

- consumer/option.go
- consumer/option_test.go
- internal/remote/remote_client.go
- producer/option.go
- producer/option_test.go
- producer/producer.go
fix https://github.com/apache/rocketmq-client-go/issues/1110 producer send msg timeout option does not take effect
```
rocketmq.NewProducer(
producer.WithSendMsgTimeout(time.Second*3),
producer.WithRetry(2),
)
```
In most cases, a fixed timeout of 3 seconds is written into the code, preventing the configuration from taking effect.
add producer option `producer.WithSendMsgTimeout(time.Microsecond*1)` and send message, no err return. (io timeout expected)
> fix: fix producer send msg timeout option does not take effect

- internal/remote/remote_client.go
- producer/producer.go
https://github.com/apache/rocketmq-client-go/issues/1112 optimize producer send async, without block (connect and sendRequest)
old version
new version
```
package main
import (
"context"
"fmt"
"time"
"github.com/apache/rocketmq-client-go/v2"
"github.com/apache/rocketmq-client-go/v2/primitive"
"github.com/apache/rocketmq-client-go/v2/producer"
)
var defaultProducer = getProducer()
func getProducer() rocketmq.Producer {
p, err := rocketmq.NewProducer(
producer.WithSendMsgTimeout(time.Second*3),
producer.WithRetry(2),
)
if err != nil {
panic(err)
}
err = p.Start()
if err != nil {
panic(err)
}
return p
}
func sendMsg(topic string, body []byte) error {
msg := primitive.NewMessage(topic, body)
ctx := context.Background()
startTime := time.Now()
err := defaultProducer.SendAsync(ctx, func(ctx …
```
> [ISSUE #1112] feat: optimize producer send async

- internal/remote/remote_client.go
https://github.com/apache/rocketmq-client-go/blob/3f9c59fdf5d4cef0994939228f40886517d42d6f/internal/remote/remote_client.go#L177-L195
the error logs 
> 2023-12-05T10:33:03+08:00 ERROR remote/remote_client.go:183 github.com/apache/rocketmq-client-go/v2/internal/remote.(*remotingClient).receiveResponse conn error, close connection {"underlayError": "read tcp 192.7.128.158:43358->192.183.1.196:9876: i/o timeout"}
when get route info from name server  timeout, just ignore the error log
ignore conn read timeout log
> fix: ignore name server connection read timeout log

- internal/remote/remote_client.go
connection close add debug log
> 2023-12-06T19:35:21+08:00	DEBUG	remote/remote_client.go:194	github.com/apache/rocketmq-client-go/v2/internal/remote.(*remotingClient).receiveResponse	conn error, close connection	{"remoteAddr": "11.167.188.81:10911", "localAddr": "30.180.112.163:55153", "underlayError": "read tcp 30.180.112.163:55153->11.167.188.81:10911: i/o timeout"}
> feat: connection add debug log

- primitive/result.go
The String() method in SendResult struct can cause a panic when MessageQueue field is nil. This is because String() method tries to access MessageQueue.String() without checking if MessageQueue is nil.
This PR adds a nil check for MessageQueue before calling its String() method. If MessageQueue is nil, it uses the string "nil" to represent it.
This solution prevents the panic and makes SendResult.String() method more robust.
XXXX
> [ISSUE #1124] fix: panic in SendResult.String

- consumer/consumer.go
- consumer/pull_consumer.go
- consumer/push_consumer.go
fix #1106
Send retry as a normal message when sendMessageBack fails. (Refer to Java SDK)
XXXX
> [ISSUE #1106] Send retry as a normal message when sendMessageBack fails

- examples/producer/delayms/main.go
- primitive/message.go
[ISSUE 1152]
support send delay message at any time 
I verify this feature use the server rocketmq v5.2.0
execute command
cd examples/producer/delayms/
build -o main main.go
// delay one and a half day，  129600s
./main  --topic=benchmark-queue-1 --endpoint=10.3.*.*:9876  --count=10  --delay=129600
> [ISSUE 1152] add feature, support message delay any time

- consumer/consumer.go
- consumer/offset_store.go
- consumer/process_queue.go
- consumer/pull_consumer.go
- consumer/push_consumer.go
- internal/request.go
- internal/trace.go
- producer/producer.go
> [ISSUE #1160] add brokerName in request protocol

- internal/trace.go
The intention here should be to initialize a slice with a capacity of  `len(ks)`  rather than initializing the length of this slice. 
The online demo: https://go.dev/play/p/q1BcVCmvidW
XX
XXXX
> fix: fix slice init length

- primitive/base.go
Fix the problem that the withRecover method cannot capture panic normally
* PanicHandler is converted from a variable to a type.
* Define a default DefaultPanicHandler method.
* WithRecover defines a variadic parameter handlers, and if none are passed, it adds DefaultPanicHandler to the handlers. 
XXXX
> fix: withRecover cannot recover panic

- consumer/push_consumer.go
- primitive/base.go
- primitive/base_test.go
https://github.com/apache/rocketmq-client-go/pull/1074#issuecomment-1837775085
in old version, we could do this
```
primitive.PanicHandler = func(i interface{}) {
msentry.CaptureMessage(fmt.Sprintf("%+v", i), nil)
}
```
but in latest version, default panic handler could not be customized.
when push consume panic, default panic handler should be called (we log and monitor the panic in default panic handler)
> make default panic handler could be customized

- internal/trace.go
fix #1194:  check trace topic message queues length before queue-select to avoid divided-by-zero panic.
> [ISSUE #1194] fix bug: divided-by-zero panic may happen during traceDispatcher#findMq

- consumer/push_consumer.go
fix pushConsumer.pause data race, when Suspend or Resume write pause, but doBalance read pause in the background.
> feat: fix push consumer pause data race
