- doc/Introduction.md
I have completed simple introduction  to use  `rocketmq client go` on macOS, including compile, installation and basic usages.
> Rocketmq client in go's introduction 

- core/api.go
- core/producer.go
- core/queue_selector.go
- core/queue_selector_test.go
- examples/orderproducer/producer.go
Send orderly function and example
> Send orderly

- cmd/producer.go
- core/api.go
- core/cfuns.go
- core/log.go
- core/log_test.go
- core/message.go
- core/message_test.go
- core/producer.go
- core/pull_consumer.go
- core/push_consumer.go
- core/version.go
- examples/orderproducer/producer.go
- examples/producer.go
- examples/pullconsumer/consumer.go
- examples/push_consumer.go
1. More Configurable fields
2. error code of call C method returned has been processed
3. Command line tools.
4. use [logrus](https://github.com/sirupsen/logrus) as log framework.
> More Configurable fields and mores

- core/api.go
- core/api_test.go
- core/log_test.go
- core/producer.go
- core/push_consumer.go
- core/queue_selector.go
- core/queue_selector_test.go
- core/utils.go
- examples/orderproducer/producer.go
- examples/producer.go
1. Implementing `SendMessageOneway` method
2. other fix: 
- Aligning fields in `String()` of config
- Optimizing `examples/producer.go`
- Optimizing definition of `MessageModel`
> Implementing SendMessageOneway

- doc/Introduction.md
1: add push order message and pull consumer
2: using `install` rather than `cp` to install dynamic library
> Enrich introduction.md 

- examples/producer.go
- examples/push_consumer.go
fix:The specified topic does not take effect when run the command:
```go
go run main.go produce --topic=demo
go run main.go consume --topic=demo
```
> fix:The specified topic does not take effect when run main.go

- .travis.yml
- README.md
- core/cfuns.go
- core/error.go
- core/log.go
- core/message.go
- core/producer.go
- core/pull_consumer.go
- core/push_consumer.go
Add .travis.yml to enable ci pipeline.
> Enabling travis CI

- README.md
fixed typo for readme
change rocketmq-client-python to rocketmq-client-go
readme.md
> [typo] Fix typo for readme

- utils/ring_buffer.go
- utils/ring_buffer_test.go
implement ring buffer
Ring Buffer
* Write(b []byte) error 
* Read(timeout time.Duration) (data []byte, err error) 
* ReadBySize(data []byte,timeout time.Duration) (n int, err error) {
* Size() uint64 
* Cap() uint64
> ring buffer

- consumer.go
- consumer_test.go
- core/producer.go
- core/push_consumer.go
- go.mod
- go.sum
- kernel/client.go
- kernel/model.go
- kernel/request.go
- kernel/response.go
- kernel/route.go
- kernel/route_test.go
- remote/client.go
- remote/codec.go
- remote/codec_test.go
- rlog/log.go
- utils/helper.go
- utils/helper_test.go
- utils/ring_buffer.go
- utils/ring_buffer_test.go
make PullConsumer Work.
- fix bugs of remote
- refactor logger
- PullConsumer can get messages from broker no
- remove cgo codes
> Pull Consumer

- consumer/consumer.go
- consumer/consumer_test.go
- consumer/offset_store.go
- consumer/process_queue.go
- consumer/push_consumer.go
- kernel/client.go
- kernel/request.go
- kernel/route.go
- remote/remote_client.go
- remote/remote_client_test.go
- utils/errors.go
- utils/files.go
Adding OffsetStore for Consumer
- Adding LocalFileStore for Broadcast mode
- Adding RemoteBrokerStore for Clustering mode
> Add OffsetStore for Consumer

- README.md
- changelog
- docs/Introduction.md
- examples/consumer/main.go
- examples/producer/main.go
- producer/producer.go
update documents for release 2.0.0-alpha1
- update README.md
- update Introduction.md
- update changelog
> Update documents for release 2.0.0-alpha1

- consumer/push_consumer.go
- examples/consumer/main.go
- examples/producer/main.go
- go.sum
- kernel/client.go
- producer/producer.go
- utils/string.go
- utils/string_test.go
fix panic bugs when topic not exist
- fix panic bugs when topic not exist
- add multiple namesrv  checking
> Fix panic bugs when topic not exist

- README.md
Add notice of native in README.md of master.
> Add notice of native in README.md

- remote/codec.go
- remote/codec_test.go
- remote/remote_client.go
- remote/remote_client_test.go
fix remote package and make unit tests pass
1. make `remote/codec_test.go` pass.
2. fix `ResponseFuture`'s `waitResponse` method to avoid potential bug.
3. fix bug in `RemotingClient`'s `receiveResponse` method.
4. make `remote/remote_client_test.go` pass
> make all remote unit tests pass

- examples/consumer/interceptor/main.go
- examples/producer/interceptor/main.go
- internal/kernel/request.go
- internal/producer/producer.go
- primitive/result.go
- primitive/result_test.go
fix message properties for producer and consumer.
add proeprties in SendMessageRequest, as well as marshal、unmarshal method. introducing new test framework: "github.com/stretchr/testify/assert".
> [ISSUE #65] Fix message missing tag  properties 

- examples/producer/async/main.go
- internal/kernel/client.go
- internal/producer/producer.go
- internal/remote/future.go
- internal/remote/remote_client.go
- internal/remote/remote_client_test.go
- primitive/ctx.go
impl producer async method.
fix remote client async timeout bug
add async method on client and producer
add remoteClient async timeout unit test
add sync producer example
> [ISSUE #98]add producer async method. resolve #98

- api.go
- consumer/consumer.go
- consumer/option.go
- consumer/pull_consumer.go
- consumer/push_consumer.go
- examples/consumer/pull/main.go
- examples/consumer/simple/main.go
- internal/client.go
- internal/remote/future.go
- internal/remote/remote_client.go
- utils/errors.go
Add PullConsumer
Add PullConsumer
add example
> [ISSUE #105] Add PullConsumer. resolve #105

- producer/producer_test.go
delete redundant assert.Nil(t, r)
delete redundant assert.Nil(t, r) in producer_test.go
XXXX
> delete redundant assert.Nil(t, r)

- consumer/push_consumer.go
- consumer/statistics.go
support statistics of consumer client
add `consume/statistics.go` file
XXXX
> [ISSUE #75] Support Statistics of client

- consumer/push_consumer.go
change `Fatal(f)` method into `Error(f)` method
All changes in `consume/push_consumer.go` file
XXXX
> [ISSUSE #75] change `Fatal(f)` method into `Error(f)` method

- internal/client.go
- internal/route_test.go
Add internal/route.go unit tests
add internal/route_test.go file
modify function named encodeMessages in internal/client.go
XXXX
> [ISSUE #75] Add internal/route.go unit tests

- consumer/consumer.go
- consumer/lock.go
- consumer/option.go
- consumer/process_queue.go
- consumer/push_consumer.go
- examples/consumer/orderly/main.go
- internal/client.go
- primitive/ctx.go
- primitive/message.go
Add orderly consumer
Add orderly consumer
add example
> [ISSUE #114] add orderly consume. resolve #114

- consumer/consumer.go
- consumer/option.go
- consumer/process_queue.go
- consumer/push_consumer.go
- examples/consumer/retry/concurrent/main.go
- examples/consumer/retry/order/main.go
- internal/client.go
- internal/constants.go
- internal/request.go
- internal/route.go
- primitive/ctx.go
add messaage sendback
add messaage sendback
> [ISSUE #118]add messaage sendback. resolve #118

- examples/consumer/delay/main.go
- examples/producer/delay/main.go
- primitive/message.go
add message delay to send
1. add method for set delaylevel
2. add producer&consumer example
> [ISSUE #122]add msg delay to send. resolve #122

- internal/client.go
- internal/mock_client.go
#128 
update mockgen command line，in order to fix generate file "import cycle not allowed" problem
when using mockgen to generate mock file ,the generated mock file could cause "import cycle not allowed". I update the mockgen command line to  fix this problem
XXXX
> [ISSUE #128]update mockgen command line

- consumer/offset_store.go
* Add locker in offset_store's update and persist
> [ISSUE #139]add locker for updating data

- .travis.yml
- api.go
- consumer/consumer.go
- consumer/interceptor.go
- examples/producer/transaction/main.go
- internal/callback.go
- internal/client.go
- internal/model.go
- internal/model_test.go
- internal/remote/remote_client.go
- internal/remote/remote_client_test.go
- internal/request.go
- internal/trace.go
- internal/utils/set.go
- primitive/message.go
- primitive/result.go
- producer/interceptor.go
- producer/option.go
- producer/producer.go
> [ISSUE #137]add transaction producer

- consumer/statistics.go
- consumer/statistics_test.go
Add consume/statistic.go unit test
add consume/statistic_test.go file
XXXX
> [ISSUE #148] add consume/statistic.go unit test

- api.go
- internal/utils/files.go
Optimize PullConsumer API
align LiteConsumer of RocektMQ
XXXX
> [ISSUE #151] Optimize PullConsumer API

- consumer/strategy.go
- consumer/strategy_test.go
- go.mod
- go.sum
merge native
- add AllocateByConsistentHash algorithm  and it's test
add AllocateByConsistentHash algorithm  and it's test
> [ISSUE#120] add AllocateByConsistentHash algorithm  and it's test

- .gitignore
- consumer/consumer.go
- consumer/option.go
- consumer/pull_consumer.go
- consumer/push_consumer.go
- examples/consumer/acl/main.go
- examples/consumer/namespace/main.go
- examples/producer/acl/main.go
- examples/producer/namespace/main.go
- internal/client.go
- internal/model.go
- internal/namesrv.go
- internal/remote/codec.go
- internal/remote/remote_client.go
- internal/response.go
- internal/route.go
- internal/utils/files.go
- producer/option.go
- producer/producer.go
#147 Support Namespace and domain of namesrv
Support Namespace and domain of namesrv
verified
> [ISSUE #147] Support Namespace and domain of namesrv

- consumer/consumer.go
- consumer/process_queue.go
- internal/utils/files.go
- primitive/result.go
> [ISSUE #190] Modify some code to be more elegant.

- consumer/offset_store.go
- consumer/offset_store_test.go
ensure offsetStore is consistent with java.
> [ISSUE #186] Fix offsetSotre

- primitive/base.go
Add ip checker exception for HTTP(s) endpoint.
modify base.go
send and consumer message with endpoint.
> Fix the domain checker was rollback before

- errors.go
- examples/consumer/pull/main.go
- internal/utils/errors.go
Fix errors of using internal codes in the exported snippet
Fix errors of using internal codes in the exported snippet
> [ISSUE #184]Fix errors of using internal codes in the exported snippet

- consumer/push_consumer.go
- examples/consumer/retry/concurrent/main.go
- primitive/ctx.go
Fix errors of comments and spelling
Fix errors of comments and spelling
XXXX
> [ISSUE #185] Fix errors of comments and spelling

- examples/main.go
> refactor(example): polish rocketmq go example

- doc/Introduction.md
modify the install method of c library
download package from apache site
see the introduction page
> doc(Readme):modify the install method of c library

- core/api.go
- core/producer.go
Support lite order producer
#217 Support lite order producer
Support lite order producer
> Support lite order producer

- core/producer.go
fix(produer):remove cycle package
fix(produer):remove cycle package
fix(produer):remove cycle package
> fix(produer):remove cycle package

- demos/orderly_push_consumer.go
- demos/producer.go
- demos/producer_orderly.go
- demos/push_consumer.go
add seperately demos
add separately demos
add separately demos
change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
> feat(demos): add separately demos

- core/api.go
- core/producer.go
- demos/orderly_push_consumer.go
- demos/producer.go
- demos/producer_orderly.go
- demos/push_consumer.go
support lite producer to send message by sharding key
support lite producer to send message by sharding key
support lite producer to send message by sharding key
> feat(producer): support lite producer to send message by sharding key

- core/api.go
- core/push_consumer.go
add set maxcachesize api to support simple flow-control
add set maxcachesize api to support simple flow-control
add set maxcachesize api to support simple flow-control
> feat(consumer): add set maxcachesize api to support simple flow-control

- README.md
Add Godoc Badge to README.md
Add Godoc Badge to README.md
See README
> Add Godoc Badge

- rlog/log.go
- add method for Logger interface
- add method for set level and log path of default log
Closes #207
> [ISSUE #207]feat: support log level and log path

- consumer/interceptor.go
- examples/consumer/trace/main.go
- examples/producer/trace/main.go
- internal/trace.go
- primitive/interceptor.go
- primitive/trace.go
- producer/interceptor.go
- add acl struct for trace config
Closes #202
> [ISSUE #202]fix: support acl  for trace

- primitive/trace.go
Fix Travis Ci error caused by trace.go format.
> fix(travis): Fix travis ci error

- consumer/option.go
- primitive/trace.go
- producer/option.go
- add instanceName to distinguish different consumer and producer object
Closes #234
> [ISSUE #234]fix: support multiple consumer&producer

- .gitignore
- benchmark/consumer.go
- core/api.go
- core/cfuns.go
- core/error.go
- core/message.go
- core/producer.go
- core/push_consumer.go
- core/queue_selector.go
- core/utils.go
- core/version.go
- demos/orderly_push_consumer.go
- demos/producer_orderly.go
- demos/push_consumer.go
- examples/main.go
- examples/producer_orderly.go
- examples/pull_consumer.go
- examples/push_consumer.go
#223 
fix(golint): fix warnings for golint check
> fix(golint): fix warnings for golint check

- primitive/message.go
- producer/option.go
- producer/selector.go
- producer/selector_test.go
- add hashQueueSelector
- use hashQueueSelector as default QueueSelector
Closes #209
> [ISSUE #209]feat: support hashQueueSelector

- go.mod
- internal/remote/remote_client.go
- use io.reader instead of scanner
Closes #252
> [ISSUE #252] feat: reduce receive memory usage

- core/api.go
- core/message.go
- core/transaction_funcs.go
- core/transaction_producer.go
- demos/transaction_producer.go
#260 add trasaction producer message
add trasaction producer message
> feat(transaction): add trasaction producer message

- core/api.go
- core/transaction_funcs.go
- demos/transaction_producer.go
#228 fix(transaction):can not do local execute and check
fix(transaction):can not do local execute and check
> fix(transaction):can not do local execute and check

- consumer/push_consumer.go
> graceful shutdown pc locker

- core/api.go
- core/message.go
- core/transaction_producer.go
- demos/transaction_producer.go
fix(golint): fix the warnings by go lint check.
fix(golint): fix the warnings by go lint check.
golint
> fix(golint): fix the warnings by go lint check.

- core/producer.go
- core/push_consumer.go
Throw exception when producer or consumer miss model
Modify the code about producer or consumer create
Pass the tests
> [ISSUE 268] Throw exception when producer or consumer miss model

- consumer/push_consumer.go
> [ISSUE  #194] consumerGroup cannot auto create

- internal/client.go
- internal/model.go
- internal/remote/remote_client.go
- internal/route.go
- internal/trace.go
- internal/utils/errors.go
- producer/producer.go
> fix CI error

- consumer/consumer.go
- consumer/offset_store.go
- consumer/push_consumer.go
- internal/client.go
- internal/mock_client.go
- internal/request.go
- internal/route.go
- internal/trace.go
- producer/producer.go
- unify request header format: XXXRequestHeader
Closes #279
> [ISSUE #279] feat(protocol): unify name of request header

- consumer/consumer.go
- internal/request.go
- use millis instead of seconds
- requestCode turn to 29
Closes #281
> [ISSUE #281] fix(protocol): SearchOffsetByTimestamp protocol bug

- internal/request.go
- delete json tag in internal/request.go
Closes #278
> [ISSUE #278] feat(protocol): remove extra json tag

- consumer/push_consumer.go
- add done chan for lifecycle close
Closes #285
> fix(consumer): goroutine leak when shutdown

- .travis.yml
- core/error.go
- core/message_test.go
- core/producer_test.go
- core/push_consumer_test.go
feat(ci): open online test cases
> feat(ci): open online test cases

- consumer/offset_store.go
- consumer/offset_store_test.go
#299 missing `fallthrough` statement in offset store read.
> [ISSUE #299] offset store read missing fallthrough for _ReadMemoryThenStore

- internal/client.go
fix https://github.com/apache/rocketmq-client-go/issues/293
> [ISSUE #293] Optimize Close of rmqClient

- .travis.yml
- consumer/push_consumer.go
- internal/client.go
fix https://github.com/apache/rocketmq-client-go/issues/271
> [ISSUE #271] Fix bugs that can't consume multiple topics in single consumer

- .travis.yml
fix(travis): use aichive link to download rocketmq binary
> fix(travis): use aichive link to download rocketmq binary

- consumer/consumer.go
- consumer/pull_consumer.go
- consumer/push_consumer.go
- internal/model.go
- producer/producer.go
- using atomic for status
Closes #318
> [ISSUE #318] fix: using atomic status for producer/consumer

- primitive/message.go
> [ISSUE #323] feat(message): remove extra code

- primitive/message.go
> fix bugs of panic when decode MessageExt

- consumer/consumer.go
- primitive/message.go
- remove extra equal method
Closes #317
> [ISSUE #317] fix(message): 错误的 equals实现

- consumer/consumer.go
- consumer/push_consumer.go
> [ISSUE #321] fix: lots of  incorrect impl

- api.go
- examples/producer/batch/main.go
- internal/request.go
- primitive/message.go
- producer/producer.go
- add batch message
- modify producer interface
Closes #331
> feat(producer): support batch message send

- examples/consumer/retry/order/main.go
- examples/consumer/simple/main.go
- examples/consumer/strategy/main.go
- examples/consumer/tag/main.go
- examples/consumer/trace/main.go
- examples/producer/acl/main.go
- examples/producer/async/main.go
- examples/producer/delay/main.go
- examples/producer/interceptor/main.go
- examples/producer/namespace/main.go
- examples/producer/simple/main.go
- examples/producer/tag/main.go
- examples/producer/trace/main.go
- examples/producer/transaction/main.go
> [ISSUE #335] feat(example): rename shutdown instead of shundown

- consumer/push_consumer.go
- internal/client.go
- internal/request.go
- modify pull timeout
- add suspend time
Closes #349
> [ISSUE #349] fix: pull timeout and suspend time is not consistent with java

- consumer/option.go
> feat: more consumer option config

- internal/client.go
> [ISSUE #358] feat: rename persistent with interval

- internal/remote/remote_client.go
- primitive/pool.go
> [ISSUE #360] feat: use pool for header codec

- consumer/statistics.go
> [ISSUE #356] feat(consumer): redesign stat

- consumer/push_consumer.go
> [ISSUE #365] fix: lock is extra when not orderly consume

- consumer/push_consumer.go
> [ISSUE #398] fix: slaveread

- primitive/errors.go
> [ISSUE #391] feat: support mq error

- consumer/push_consumer.go
> fix(consumer): use sync offset fix instead if async

- README.md
doc(readme): add Due Diligence link in the readme file
> doc(readme): add Due Diligence link in the readme file

- internal/client.go
close #441 
fix(heatbeat): change consume type to avoid fastjson decode error in lower broker version
> fix(heatbeat): change consume type to avoid fastjson decode error in lower broker version

- internal/client.go
> [ISSUE #446] correct msgid using unique id.

- internal/remote/remote_client.go
> [ISSUE #443] Ignore eof error when conn closed.

- consumer/push_consumer.go
- internal/client.go
- internal/trace.go
- primitive/message.go
- primitive/trace.go
> [ISSUE #462] fix the trace message was send failed.

- README.md
- internal/client.go
> [ISSUE #467]modify version and readme to release 2.0.0

- README.md
close #467
[ISSUE #467] Modify readme to release version 2.0.0
> [ISSUE #467] Modify readme to release version 2.0.0

- consumer/push_consumer.go
- internal/client.go
The message mode, ctype and where was wrong in the heartbeat data，now we can get them form inner client
> [ISSUE #471] The message mode, ctype and where was wrong in the heartbeat data

- README.md
> Fix README.md typo.

- internal/namesrv.go
> [ISSUE #527] fix(nameserver): panic in nameserver size is changed.

- consumer/pull_consumer.go
#513 #523 fix panic when pullconsumer started.
defaultOpts.Namesrv = srvs
XXXX
> [ISSUE #513] fix panic when pullconsumer started.

- consumer/push_consumer.go
Change-Id: Iba9a65d5e0bfdc513ee65e0f121b8cc2b4a76ad1
fix PullOffsetIllegal delete processQueue error
consumer/push_consumer.go:708
looks good to me 
> [ISSUE #520]fix(pushConsumer):fix PullOffsetIllegal delete processQueue error

- primitive/nsresolver.go
- primitive/nsresolver_test.go
> feat: incorrect merge

- .travis.yml
- core/message.go
This pull request fixes the string truncation bug.
>  fix string truncation issue

- consumer/push_consumer.go
PullInterval unit is ms, see https://github.com/apache/rocketmq/search?q=pullInterval
> [ISSUE #640]fix PullInterval unit.

- consumer/consumer.go
- consumer/push_consumer.go
- consumer/statistics.go
- consumer/statistics_test.go
Optimization for goroutine of stat creation
XX
XXXX
> [ISSUE #678] optimizing goroutine of Stat creation

- primitive/base.go
- primitive/base_test.go
- primitive/message.go
- primitive/result.go
> [ISSUE #695] Feat: support IPV6

- rlog/log.go
add missing log level: fatal
XX
XXXX
> fix: add missing log level fatal

- consumer/process_queue.go
- consumer/push_consumer.go
- internal/client.go
- internal/model.go
- internal/model_test.go
- internal/request.go
- rlog/log.go
issue #681 
- Add request handle logic for ReqResetConsumerOffset
- Fix some bug of ResetOffset func and expose it
- Add unit test for offsetTable body decode
XXXX
> [ISSUE #681]feat(internal): support reset consumer offset

- consumer/push_consumer.go
- internal/client.go
- internal/namesrv.go
- internal/route.go
- producer/producer.go
> [ISSUE #699] Fix the bug caused in HA cluster when master broker node is down

- consumer/pull_consumer.go
- internal/route.go
> [ISSUE #716] Fix the bug caused in HA cluster in pull_consumer

- consumer/consumer.go
set subversion when buildSubscriptionData to fix overwrite subscription don't work
> (fix): set subversion when buildSubscriptionData

- consumer/push_consumer.go
> [ISSUE #722] fix the bug caused by failover in consumer

- consumer/push_consumer.go
> [ISSUE #731] Optimize the update offset logic

- primitive/pool.go
Signed-off-by: xuweiwei <xuweiwei_yewu@cmss.chinamobile.com>
#752
headerPool.Put(&d) -> headerPool.Put(&d)
> [ISSUE #752] change argument to pointer-like to avoid allocations

- internal/client.go
> [issue #778] Build instance name with nanosecond

- consumer/push_consumer.go
Fix: `queueMaxSpanFlowControlTimes` is not changed.
XX
XXXX
> fix queueMaxSpanFlowControlTimes not change

- examples/producer/async/main.go
> [ISSUE #810] fix async producer example

- producer/producer.go
fix stack overflow caused by recursive calls
> fix(sendOneWay): fix stack overflow caused by recursive calls

- consumer/message_util.go
- examples/consumer/rpc/main.go
- internal/client.go
message_utils.go is in internal，external package can't import it
> feat: exchange messages_utils dir

- producer/producer.go
close #847 
fix ctx transfer fail 
> [ISSUE #847] fix primitive.WithMethod ctx transfer

- consumer/push_consumer.go
- internal/client.go
- producer/producer.go
fmt when i read source code.
XX
XXXX
- [] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
> feat(fmt): compare slice length directly

- api.go
- consumer/push_consumer.go
Add method for pushConsumer 
```go
// Suspend the consumption
Suspend()
// Resume the consumption
Resume()
```
XX
XXXX
> add some methods for pushConsumer

- consumer/push_consumer.go
> [ISSUE #843] fix request offset will not be changed in some case

- examples/consumer/simple/main.go
> a liitle improvement use chan instead

- consumer/push_consumer.go
> [ISSUE #780]avoid sendmessage back with origin message body in request.

- api.go
close #869 Fix consumer api comments in api.go
> [ISSUE #869] Fix: Consumer api comments

- .travis.yml
close #872 
fix code coverage shell error in travis ci yml.
> [ISSUE #872] fix code coverage shell error in travis ci yml.

- internal/route.go
close #882 
see detail https://github.com/apache/rocketmq/blob/4b5270a724d100ab87f56fdd06a4ba57571a02b9/client/src/main/java/org/apache/rocketmq/client/impl/MQAdminImpl.java#L143
https://github.com/apache/rocketmq/blob/4b5270a724d100ab87f56fdd06a4ba57571a02b9/client/src/main/java/org/apache/rocketmq/client/impl/MQAdminImpl.java#L65
Sometimes I met the error `the topic=xxx route info not found, it may not exist`, but Java works well in test environment.
So just keep the same timeout as Java to solve the problem.
XX
XXXX
> [ISSUE #882] keep queryTopicRouteInfoFromServer timeout the same as Java

- README.md
> [ISSUE #862]Update readme file according to the new features in the latest release version.

- consumer/statistics.go
fix: wrong stats log(#907 )
fix: wrong stats log(#907 )
fix: wrong stats log(#907 )
> [ISSUE #907]remove useless stats log (#907)

- consumer/process_queue.go
close #904 
Fixed:when msgCh full,can't release the pq.mutex lock,removeMessage method will block.
Fixed:when msgCh full,can't release the pq.mutex lock,removeMessage method will block.
Fixed:when msgCh full,can't release the pq.mutex lock,removeMessage method will block.
> [ISSUE #904] fix:pq.mutex lock blocked.

- docs/Introduction.md
> [ISSUE #912] Update introduction.md

- internal/utils/files.go
修复消费者广播模式下，多进程访问文件bug（fix  question #922）
> [ISSUE #922]close file after it was read in internal fiel utils.

- consumer/pull_consumer.go
> [ISSUE #939]Pull or poll message support message trace

- consumer/pull_consumer.go
- consumer/push_consumer.go
- internal/validators.go
> [ISSUE #935]fix consumer option validate

- consumer/pull_consumer.go
- consumer/push_consumer.go
> [ISSUE #942]correct name typo

- consumer/pull_consumer.go
- consumer/push_consumer.go
- internal/client.go
fix some spell mistakes
fix "UNKOWN" to "UNKNOWN"
fix "consumerid" to "consumerId"
All the tests passed
> fix some spell mistakes

- consumer/offset_store.go
- internal/response.go
Fix small typo which is only used in a couple of places. This change attempts to rectify the typo before being referenced in  more places :)
XX
XXXX
> Fix response ResQueryNotFound typo

- consumer/push_consumer.go
> [ISSUE #956]fix reset offset remove pq

- consumer/process_queue.go
- consumer/push_consumer.go
push consumer enable getting offset diff map, key: topic, value: offset difference
XX
XXXX
> push consumer enable getting offset diff map

- api.go
add api GetOffsetDiffMap
XX
XXXX
> add api GetOffsetDiffMap

- consumer/consumer.go
- internal/model.go
- internal/utils/set.go
> [ISSUE #961] Fix: data race when update subversion for consumer

- consumer/push_consumer.go
> [ISSUE #970]fix:logic error when reset retry message's origin topic

- consumer/consumer.go
- consumer/push_consumer.go
> [ISSUE #994] Fix: unlock all queues when consumer shutdown in orderly model

- consumer/consumer.go
> [ISSUE #1024] fix: unsubscribed topic queues not dropped

- internal/model.go
Fix bug from #962 
When using tags, there are some problems in the `clone` method
XX
XXXX
> fix wrong add for set when tags are set

- internal/client.go
> [ISSUE #1056] fix: When the consumer and producer have the same topic, the consumer fails to update the topic.

- consumer/push_consumer.go
- internal/model.go
…with_goroutine## What is the purpose of the change
增加锁，防止并发冲突
add lock for SubscriptionData to protect datarace
> add lock for SubscriptionData

- internal/route.go
> [ISSUE #1076] fix: sort Topic routing information to ensure that order messages are sent normally

- examples/producer/transaction/main.go
- primitive/message.go
- producer/producer.go
> Fix typo Unknow -> Unknown

- consumer/statistics.go
fix get push consumer consumer rt
should fix topicAndGroupConsumeRT
XXXX
> fix get push consumer consumer rt

- consumer/push_consumer.go
- primitive/message.go
> [ISSUE #166] fix concurrency for message property string

- primitive/nsresolver.go
feat: check domain empty string
> feat: check domain empty string

- docs/Introduction.md
Fix the error description under PushConsumer interface
> fix typo: PullConsumer -> PushConsumer in Introduction.md

- producer/producer.go
fixed callback function execution start context being canceled
* after the callback function is executed, cancel through defer.
XXXX
> fix:callback function execution start context being canceled

- consumer/pull_consumer.go
fix bug:seek offset won't work due to wrong map key type #1183
> [ISSUE #1183] fix bug:seek offset won't work due to wrong map key type

- admin/admin.go
- internal/mock_namesrv.go
- internal/namesrv.go
- internal/route.go
> [ISSUE #1205]Exposing cluster from admin
